# Site settings
title: twocentstudios
email: chris@twocentstudios.com
description: > # this means to ignore newlines until "baseurl:"
  A coding blog covering iOS, Swift, and other programming topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twocentstudios.com" # the base hostname & protocol for your site
twitter_username: twocentstudios
github_username:  twocentstudios

# Build settings
markdown: kramdown
